version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'  # changed to avoid local conflict

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - db

  backend:
    build: ./server
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/todo
    depends_on:
      - db
    volumes:
      - ./server:/app

  frontend:
    build: ./todos
    ports:
      - '5173:5173'
    depends_on:
      - backend
    volumes:
      - ./todos:/app
      - /app/node_modules